/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.alertavert.constructs;

import lombok.extern.java.Log;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.context.properties.ConfigurationPropertiesScan;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.stereotype.Component;

@SpringBootApplication
@EnableConfigurationProperties
@ConfigurationPropertiesScan
@Component
@Log
public class App {

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
}
